# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TodayNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #网络请求
  pod 'Alamofire'
  #
  pod 'SwiftyJSON'
  pod 'HandyJSON', '~> 4.1.1'

pod 'Kingfisher'
pod 'IBAnimatable'
# 主题更换 
pod 'SwiftTheme'

  # Pods for TodayNews

  target 'TodayNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodayNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
